# Generated by Django 6.0 on 2026-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_transcript', models.TextField(blank=True, null=True)),
                ('translated_transcript', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
