# Generated by Django 6.0 on 2026-01-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='detected_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
