# Generated by Django 6.0 on 2026-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_transcription_detected_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='structured_segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
