# Generated by Django 6.0 on 2026-01-27 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_transcription_structured_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='detected_language',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='translated_transcript',
        ),
        migrations.AddField(
            model_name='transcription',
            name='normalized_english',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcription',
            name='raw_transcript',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcription',
            name='structured_segments',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
