# Generated by Django 6.0 on 2026-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_remove_transcription_detected_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='normalized_english',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='raw_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='structured_segments',
            field=models.JSONField(default=list),
        ),
    ]
