# Generated by Django 5.2.10 on 2026-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_alter_transcription_normalized_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='status',
            field=models.CharField(default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
