# Generated by Django 5.2.10 on 2026-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0006_transcription_status_alter_transcription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
