# Generated by Django 5.2.10 on 2026-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0007_transcription_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED'), ('ERROR', 'ERROR')], default='UPLOADED', max_length=20),
        ),
    ]
