# Generated by Django 5.2.10 on 2026-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0008_transcription_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='current_stage',
            field=models.CharField(default='FILE_RECEIVED', max_length=50),
        ),
    ]
