# Generated by Django 5.2.10 on 2026-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0009_transcription_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='progress_logs',
            field=models.JSONField(default=list),
        ),
    ]
