# Generated by Django 5.2.10 on 2026-02-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0010_transcription_progress_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='progress_logs',
        ),
    ]
